/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState } from 'react';
import { AgentMode, ModelServerConfig } from '../types';
import ThemeSelectorDropdown from './ThemeSelectorDropdown';
import { ThemeMode, AccentColor, ACCENT_COLORS } from '../utils/theme';
import { 
  Cpu, Sparkles, MessageSquare, Code, Search, FileText, CheckCircle, 
  ChevronDown, Image, Mic, Volume2, Video, Box, Globe, Workflow, 
  ShieldAlert, GitBranch, History, Layout, Eye, Layers, Bot,
  PanelLeft, PanelLeftClose, PanelLeftOpen, PanelRight, PanelRightClose, PanelRightOpen
} from 'lucide-react';

export interface WorkspaceOption {
  id: string;
  label: string;
  category: string;
  icon: React.ReactNode;
  mode: AgentMode;
  workspaceTab?: 'flow' | 'editor' | 'diagnostics' | 'docs' | 'pipeline' | 'multiagent' | 'git' | 'self_heal' | 'time_travel' | 'wireframe';
  multimodalFeature?: string;
  description: string;
}

export const WORKSPACE_OPTIONS: WorkspaceOption[] = [
  { id: 'chat', label: 'General AI Chat', category: 'Core Assistants', icon: <MessageSquare className="w-4 h-4 text-blue-400" />, mode: 'chat', workspaceTab: 'editor', description: 'Conversational assistant for architecture & queries' },
  { id: 'code', label: 'Code Generation & IDE', category: 'Core Assistants', icon: <Code className="w-4 h-4 text-emerald-400" />, mode: 'code', workspaceTab: 'editor', description: 'Full-stack software engineering & workspace editor' },
  { id: 'agent_flow', label: 'Agent Execution Flow', category: 'Core Assistants', icon: <Workflow className="w-4 h-4 text-purple-400" />, mode: 'code', workspaceTab: 'flow', description: 'View & manage step-by-step flow generated by code agent' },
  { id: 'research', label: 'Deep Research Studio', category: 'Core Assistants', icon: <Search className="w-4 h-4 text-amber-400" />, mode: 'research', workspaceTab: 'docs', description: 'Comprehensive web & document synthesis' },
  
  { id: 'wf_builder', label: 'Multi-Agent Workflow Builder', category: 'Workflow & Automation', icon: <Workflow className="w-4 h-4 text-purple-400" />, mode: 'code', workspaceTab: 'pipeline', description: 'Drag-and-drop pipeline canvas & decision nodes' },
  { id: 'multiagent', label: 'Multi-Agent System', category: 'Workflow & Automation', icon: <Bot className="w-4 h-4 text-cyan-400" />, mode: 'code', workspaceTab: 'multiagent', description: 'Topology, A2A messaging, MCP context & agent traces' },
  { id: 'self_heal', label: 'Self-Healing Debugger', category: 'Workflow & Automation', icon: <ShieldAlert className="w-4 h-4 text-rose-400" />, mode: 'code', workspaceTab: 'self_heal', description: 'Autonomous error detection & auto-patching' },
  { id: 'spec_code', label: 'Wireframes & UML Studio', category: 'Workflow & Automation', icon: <Layers className="w-4 h-4 text-indigo-400" />, mode: 'code', workspaceTab: 'wireframe', description: 'Upload, view, manage & analyze UML diagrams, wireframes & specs' },

  { id: 'tti', label: 'Text-to-Image Synthesis', category: 'Multimodal Studio', icon: <Image className="w-4 h-4 text-pink-400" />, mode: 'multimodal', workspaceTab: 'editor', multimodalFeature: 'text_to_image', description: 'Generate realistic assets & UI mockups from prompt' },
  { id: 'itt', label: 'Image-to-Text & Vision OCR', category: 'Multimodal Studio', icon: <Eye className="w-4 h-4 text-cyan-400" />, mode: 'multimodal', workspaceTab: 'editor', multimodalFeature: 'image_to_text', description: 'Analyze screenshots, diagrams, and image content' },
  { id: 'stt', label: 'Speech-to-Text (STT)', category: 'Multimodal Studio', icon: <Mic className="w-4 h-4 text-red-400" />, mode: 'multimodal', workspaceTab: 'editor', multimodalFeature: 'stt', description: 'Transcribe audio recordings and live mic speech' },
  { id: 'tts', label: 'Text-to-Speech (TTS)', category: 'Multimodal Studio', icon: <Volume2 className="w-4 h-4 text-green-400" />, mode: 'multimodal', workspaceTab: 'editor', multimodalFeature: 'tts', description: 'Convert written text into natural neural speech' },
  { id: 'video', label: 'Text-to-Video Generator', category: 'Multimodal Studio', icon: <Video className="w-4 h-4 text-violet-400" />, mode: 'multimodal', workspaceTab: 'editor', multimodalFeature: 'text_to_video', description: 'Generate high-definition AI videos' },
  { id: '3d', label: 'Text-to-3D Asset Engine', category: 'Multimodal Studio', icon: <Box className="w-4 h-4 text-amber-500" />, mode: 'multimodal', workspaceTab: 'editor', multimodalFeature: 'text_to_3d', description: 'Synthesize 3D models & meshes' },
  { id: 'translate', label: 'Language Translation', category: 'Multimodal Studio', icon: <Globe className="w-4 h-4 text-teal-400" />, mode: 'multimodal', workspaceTab: 'editor', multimodalFeature: 'translation', description: 'Multilingual neural translation' },

  { id: 'docs', label: 'Documentation Studio', category: 'Testing & Tools', icon: <FileText className="w-4 h-4 text-yellow-400" />, mode: 'documentation', workspaceTab: 'docs', description: 'Generate system guides and API documentation' },
  { id: 'testing', label: 'Testing & Diagnostics', category: 'Testing & Tools', icon: <CheckCircle className="w-4 h-4 text-green-400" />, mode: 'testing', workspaceTab: 'diagnostics', description: 'Run automated unit & integration test suites' },
  { id: 'git', label: 'Git Control Panel', category: 'Testing & Tools', icon: <GitBranch className="w-4 h-4 text-orange-400" />, mode: 'code', workspaceTab: 'git', description: 'Version control commits, branches, and diffs' },
  { id: 'history', label: 'Time Travel History', category: 'Testing & Tools', icon: <History className="w-4 h-4 text-sky-400" />, mode: 'code', workspaceTab: 'time_travel', description: 'Snapshot timeline & workspace rollbacks' },
];

interface WorkspaceHeaderBarProps {
  activeOptionId: string;
  onSelectOption: (option: WorkspaceOption) => void;
  modelConfig: ModelServerConfig;
  theme: ThemeMode;
  setTheme: (t: ThemeMode) => void;
  accentColor: AccentColor;
  setAccentColor: (a: AccentColor) => void;
  onOpenModelSelector: () => void;
  isLeftPanelCollapsed?: boolean;
  onToggleLeftPanel?: () => void;
  isRightPanelCollapsed?: boolean;
  onToggleRightPanel?: () => void;
}

export default function WorkspaceHeaderBar({
  activeOptionId,
  onSelectOption,
  modelConfig,
  theme,
  setTheme,
  accentColor,
  setAccentColor,
  onOpenModelSelector,
  isLeftPanelCollapsed = false,
  onToggleLeftPanel,
  isRightPanelCollapsed = false,
  onToggleRightPanel,
}: WorkspaceHeaderBarProps) {
  const [isOpen, setIsOpen] = useState(false);
  const activeOpt = WORKSPACE_OPTIONS.find(o => o.id === activeOptionId) || WORKSPACE_OPTIONS[0];

  const activeAccent = ACCENT_COLORS[accentColor] || ACCENT_COLORS.indigo;

  const getModelLabel = () => {
    if (modelConfig.type === 'gemini') return modelConfig.selectedModel || 'gemini-3.6-flash';
    if (modelConfig.type === 'ollama' || modelConfig.type === 'local_llm') {
      const prov = modelConfig.activeLocalProvider || 'ollama';
      const conf = modelConfig.localConfigs?.[prov];
      const activeModel = conf?.selectedModel || modelConfig.selectedModel || 'llama3';
      return `${prov.toUpperCase()}: ${activeModel}`;
    }
    return `${modelConfig.type.toUpperCase()}: ${modelConfig.selectedModel || 'default'}`;
  };

  const categories = Array.from(new Set(WORKSPACE_OPTIONS.map(o => o.category)));

  return (
    <header className="h-12 border-b border-slate-800 bg-slate-900/90 backdrop-blur px-3 flex items-center justify-between gap-2 z-40 relative">
      {/* Left: Brand + Toggle Left Panel + Single Workspace Selector Dropdown */}
      <div className="flex items-center gap-2">
        {onToggleLeftPanel && (
          <button
            type="button"
            onClick={onToggleLeftPanel}
            className="p-1.5 rounded-lg bg-slate-800/80 hover:bg-slate-700 text-slate-300 hover:text-white border border-slate-700 transition cursor-pointer"
            title={isLeftPanelCollapsed ? "Expand Left Panel (Files)" : "Minimize Left Panel (Files)"}
          >
            {isLeftPanelCollapsed ? <PanelLeftOpen className="w-4 h-4 theme-accent-text" /> : <PanelLeftClose className="w-4 h-4" />}
          </button>
        )}

        <div className="flex items-center gap-2 font-bold text-white text-sm">
          <img src="/eka.svg" alt="Eka Studio Logo" className="w-6 h-6 rounded-md shadow-sm shrink-0" />
          <span className="hidden sm:inline font-mono tracking-tight">Eka - Agentic AI Studio</span>
        </div>

        {/* Workspace Dropdown */}
        <div className="relative">
          <button
            type="button"
            onClick={() => setIsOpen(!isOpen)}
            className="flex items-center gap-2 bg-slate-800/90 hover:bg-slate-700 text-slate-200 border border-slate-700 px-3 py-1.5 rounded-lg text-xs font-medium transition cursor-pointer shadow-sm"
          >
            {activeOpt.icon}
            <span className="font-semibold">{activeOpt.label}</span>
            <ChevronDown className={`w-3.5 h-3.5 text-slate-400 transition-transform ${isOpen ? 'rotate-180' : ''}`} />
          </button>

          {isOpen && (
            <>
              <div className="fixed inset-0 z-40" onClick={() => setIsOpen(false)} />
              <div className="absolute top-full left-0 mt-1 w-80 max-h-[80vh] overflow-y-auto bg-slate-900 border border-slate-800 rounded-xl shadow-2xl z-50 p-2 space-y-3">
                {categories.map(cat => (
                  <div key={cat}>
                    <div className="text-[10px] font-mono font-bold uppercase tracking-wider text-slate-400 px-2 py-1">
                      {cat}
                    </div>
                    <div className="space-y-0.5">
                      {WORKSPACE_OPTIONS.filter(o => o.category === cat).map(opt => (
                        <button
                          key={opt.id}
                          type="button"
                          onClick={() => {
                            onSelectOption(opt);
                            setIsOpen(false);
                          }}
                          className={`w-full text-left px-2.5 py-1.5 rounded-lg text-xs flex items-center gap-2.5 transition cursor-pointer ${
                            opt.id === activeOpt.id
                              ? 'theme-accent-badge font-semibold'
                              : 'hover:bg-slate-800/80 text-slate-300'
                          }`}
                        >
                          {opt.icon}
                          <div className="flex-1 min-w-0">
                            <div className="truncate font-medium">{opt.label}</div>
                            <div className="text-[10px] text-slate-400 truncate font-normal">{opt.description}</div>
                          </div>
                        </button>
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            </>
          )}
        </div>
      </div>

      {/* Right Controls: Selected Model badge, Theme, Settings */}
      <div className="flex items-center gap-2">
        <button
          type="button"
          onClick={onOpenModelSelector}
          className="flex items-center gap-1.5 theme-accent-badge px-2.5 py-1 rounded-md text-[11px] font-mono transition cursor-pointer"
          title="Click to view/change Active AI Model"
        >
          <Cpu className="w-3.5 h-3.5 theme-accent-text" />
          <span className="max-w-[140px] truncate font-semibold">{getModelLabel()}</span>
        </button>

        <ThemeSelectorDropdown
          theme={theme}
          onThemeChange={setTheme}
          accentColor={accentColor}
          onAccentChange={setAccentColor}
        />

        {onToggleRightPanel && (
          <button
            type="button"
            onClick={onToggleRightPanel}
            className="p-1.5 rounded-lg bg-slate-800/80 hover:bg-slate-700 text-slate-300 hover:text-white border border-slate-700 transition cursor-pointer"
            title={isRightPanelCollapsed ? "Expand Right Panel (AI Chat)" : "Minimize Right Panel (AI Chat)"}
          >
            {isRightPanelCollapsed ? <PanelRightOpen className="w-4 h-4 theme-accent-text" /> : <PanelRightClose className="w-4 h-4" />}
          </button>
        )}
      </div>
    </header>
  );
}

