/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import React, { useState, useEffect } from 'react';
import { Mail, Play, Square, RefreshCw, CheckCircle2, AlertCircle, Terminal, HardDrive } from 'lucide-react';

export function LocalMailServerSettings() {
  const [isRunning, setIsRunning] = useState<boolean>(false);
  const [loading, setLoading] = useState<boolean>(false);
  const [statusMessage, setStatusMessage] = useState<string | null>(null);
  const [port] = useState<number>(1025);

  const fetchStatus = async () => {
    try {
      const res = await fetch('/api/mailserver/status');
      const data = await res.json();
      setIsRunning(!!data.running);
    } catch (err: any) {
      setIsRunning(false);
    }
  };

  useEffect(() => {
    fetchStatus();
  }, []);

  const handleStart = async () => {
    setLoading(true);
    setStatusMessage(null);
    try {
      const res = await fetch('/api/mailserver/start', { method: 'POST' });
      const data = await res.json();
      setIsRunning(!!data.running);
      setStatusMessage(data.message || 'Started Python Mail Server.');
    } catch (err: any) {
      setStatusMessage(`Error starting mail server: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  const handleStop = async () => {
    setLoading(true);
    setStatusMessage(null);
    try {
      const res = await fetch('/api/mailserver/stop', { method: 'POST' });
      const data = await res.json();
      setIsRunning(!!data.running);
      setStatusMessage(data.message || 'Stopped Mail Server.');
    } catch (err: any) {
      setStatusMessage(`Error stopping mail server: ${err.message}`);
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="space-y-4 font-mono text-xs">
      <div className="p-3.5 bg-slate-900/80 border border-slate-800 rounded-xl space-y-3">
        {/* Header Bar */}
        <div className="flex items-center justify-between border-b border-slate-800 pb-2">
          <div className="flex items-center gap-2 text-indigo-400 font-bold">
            <Mail className="w-4 h-4" />
            <span>Local Python SMTP Mail Server</span>
          </div>

          <div className="flex items-center gap-2">
            <span
              className={`text-[10px] px-2 py-0.5 rounded border flex items-center gap-1 font-bold ${
                isRunning
                  ? 'bg-emerald-950 text-emerald-400 border-emerald-800'
                  : 'bg-slate-950 text-slate-400 border-slate-800'
              }`}
            >
              {isRunning ? <CheckCircle2 className="w-3 h-3 text-emerald-400" /> : <AlertCircle className="w-3 h-3 text-amber-400" />}
              {isRunning ? `Running on Port ${port}` : 'Stopped'}
            </span>

            <button
              type="button"
              onClick={fetchStatus}
              className="p-1 text-slate-400 hover:text-white rounded hover:bg-slate-800 transition cursor-pointer"
              title="Refresh Status"
            >
              <RefreshCw className="w-3.5 h-3.5" />
            </button>
          </div>
        </div>

        <p className="text-[11px] text-slate-400 font-sans">
          Runs a local Python SMTP debugging server (<code className="text-indigo-300">smtp_server.py</code>) on port 1025 to catch and inspect all outbound test emails generated by workflow components and email dispatch nodes.
        </p>

        {/* Server Details Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-3 gap-2 p-2.5 bg-slate-950 rounded-lg border border-slate-800 text-[11px]">
          <div>
            <span className="text-slate-500 block text-[10px]">Host:</span>
            <span className="text-slate-200 font-bold">127.0.0.1 / localhost</span>
          </div>
          <div>
            <span className="text-slate-500 block text-[10px]">SMTP Port:</span>
            <span className="text-slate-200 font-bold">{port}</span>
          </div>
          <div>
            <span className="text-slate-500 block text-[10px]">Script:</span>
            <span className="text-indigo-400 font-bold">smtp_server.py</span>
          </div>
        </div>

        {statusMessage && (
          <div className="p-2 rounded bg-slate-950 border border-slate-800 text-slate-300 text-[11px] flex items-center gap-2">
            <Terminal className="w-3.5 h-3.5 text-indigo-400 shrink-0" />
            <span>{statusMessage}</span>
          </div>
        )}

        {/* Control Buttons */}
        <div className="flex items-center gap-2 pt-1">
          {isRunning ? (
            <button
              type="button"
              onClick={handleStop}
              disabled={loading}
              className="flex-1 bg-rose-600 hover:bg-rose-500 disabled:opacity-50 text-white font-bold py-2 rounded-lg transition flex items-center justify-center gap-2 cursor-pointer shadow"
            >
              <Square className="w-3.5 h-3.5" />
              {loading ? 'Stopping Server...' : 'Stop Local Mail Server'}
            </button>
          ) : (
            <button
              type="button"
              onClick={handleStart}
              disabled={loading}
              className="flex-1 bg-emerald-600 hover:bg-emerald-500 disabled:opacity-50 text-white font-bold py-2 rounded-lg transition flex items-center justify-center gap-2 cursor-pointer shadow"
            >
              <Play className="w-3.5 h-3.5" />
              {loading ? 'Starting Python Server...' : 'Start Python Mail Server (Port 1025)'}
            </button>
          )}
        </div>
      </div>
    </div>
  );
}
