/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Router } from 'express';
import path from 'path';
import fs from 'fs/promises';
import { generateText, nowContext } from '../shared/llm.js';
import { getWorkspaceDir, collectDirFiles } from '../shared/workspace.js';

const router = Router();

// POST /api/agent/document
router.post('/', async (req, res) => {
  const { targetPath, prompt, customConfig } = req.body;
  const WORKSPACE_DIR = getWorkspaceDir();
  try {
    const absTarget = path.join(WORKSPACE_DIR, targetPath || '');
    if (!absTarget.startsWith(WORKSPACE_DIR)) return res.status(403).json({ success: false, error: 'Access denied.' });

    let codeContext = '';
    const contextLabel = targetPath || 'workspace root';
    const stats = await fs.stat(absTarget);

    if (stats.isDirectory()) {
      const files = await collectDirFiles(absTarget, WORKSPACE_DIR);
      codeContext = files.map(f => `### File: \`${f.path}\`\n\`\`\`\n${f.content.slice(0, 3000)}\n\`\`\``).join('\n\n');
    } else {
      const content = await fs.readFile(absTarget, 'utf8');
      codeContext = `### File: \`${targetPath}\`\n\`\`\`\n${content}\n\`\`\``;
    }

    const systemInstruction = `${nowContext()}

You are an expert Technical Writer specializing in software documentation.

Generate a comprehensive, professional Markdown documentation file for the provided code.

The documentation MUST include:
# Documentation: [Module/Project Name]

> **Generated by:** Eka Agentic AI Platform
> **Target:** \`${contextLabel}\`

---

## Overview
[What this module/project does, its purpose and responsibilities]

## Architecture & Design
[High-level design, patterns used, how components relate]

## Installation & Setup
[Prerequisites, how to install and configure]

## API Reference
[For each function/class/method: signature, parameters, return value, description, example]

## Usage Examples
[Complete, runnable code examples for common use-cases]

## Configuration
[All configurable options with defaults and explanations]

## Error Handling
[Common errors, how to handle them]

## Contributing
[How to contribute, coding standards]

---
*Documentation generated by Eka Agentic AI Platform*

Rules:
- Be thorough and precise
- Use proper markdown formatting
- Code examples must be in properly labeled fenced code blocks`;

    const result = await generateText({
      customConfig,
      prompt: `Generate complete documentation for: ${prompt || contextLabel}\n\n${codeContext}`,
      systemInstruction,
      logType: 'Documentation'
    });

    const mdContent = result.text || '';
    const docsDir = path.join(process.cwd(), 'app-output', 'documentation');
    await fs.mkdir(docsDir, { recursive: true });

    const safeTarget = (targetPath || 'workspace').replace(/[/\\]/g, '-').replace(/[^a-zA-Z0-9-_]/g, '').slice(0, 50);
    const timestamp = new Date().toISOString().replace(/[:.]/g, '-').slice(0, 19);
    const fileName = `docs-${safeTarget}-${timestamp}.md`;
    await fs.writeFile(path.join(docsDir, fileName), mdContent, 'utf8');

    res.json({ success: true, filePath: `app-output/documentation/${fileName}`, content: mdContent });
  } catch (error: any) {
    console.error('Documentation error:', error);
    res.status(500).json({ success: false, error: error.message });
  }
});

export default router;
